apiVersion: v1
kind: Secret
metadata:
  name: atb-secrets
  labels: {{ include "atb.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.postgresql.postgresqlPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default "change_me_prod" | quote }}
  fedapay-api-key: {{ .Values.secrets.fedapayApiKey | quote }}
  fedapay-webhook-secret: {{ .Values.secrets.fedapayWebhookSecret | quote }}
  fedapay-sandbox: {{ .Values.secrets.fedapaySandbox | default "false" | quote }}
  mtn-momo-api-user: {{ .Values.secrets.mtnMomoApiUser | quote }}
  mtn-momo-api-key: {{ .Values.secrets.mtnMomoApiKey | quote }}
  mtn-momo-subscription-key: {{ .Values.secrets.mtnMomoSubscriptionKey | quote }}
  mtn-momo-sandbox: {{ .Values.secrets.mtnMomoSandbox | default "false" | quote }}
  cinetpay-api-key: {{ .Values.secrets.cinetpayApiKey | quote }}
  cinetpay-site-id: {{ .Values.secrets.cinetpaySiteId | quote }}
  cinetpay-sandbox: {{ .Values.secrets.cinetpaySandbox | default "false" | quote }}
  mansa-api-key: {{ .Values.secrets.mansaApiKey | quote }}
  mansa-email: {{ .Values.secrets.mansaEmail | default "api@atb.bj" | quote }}
  sentinel-client-id: {{ .Values.secrets.sentinelClientId | quote }}
  sentinel-client-secret: {{ .Values.secrets.sentinelClientSecret | quote }}
  planet-api-key: {{ .Values.secrets.planetApiKey | quote }}
