sonar.projectKey=atb-agri-trace
sonar.projectName=ATB AgriTrace Bénin
sonar.projectVersion=1.0.0
sonar.sources=packages/
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/build/**,**/dist/**
sonar.language=multi
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*
sonar.typescript.lcov.reportPaths=packages/web-buyer/coverage/lcov.info,packages/web-admin/coverage/lcov.info
