/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CertificateRegistry__factory } from "./CertificateRegistry__factory";
export { LotRegistry__factory } from "./LotRegistry__factory";
export { MultiSigWallet__factory } from "./MultiSigWallet__factory";
export { ProductorIdentity__factory } from "./ProductorIdentity__factory";
