/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateRegistry } from "./CertificateRegistry";
export type { LotRegistry } from "./LotRegistry";
export type { MultiSigWallet } from "./MultiSigWallet";
export type { ProductorIdentity } from "./ProductorIdentity";
